apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  labels:
    app.kubernetes.io/instance: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: celery-worker
        image: bitsean/crypto_trader:1.7
        command: ["celery", "-A", "crypto_trader", "worker", "-l", "info"]
        env:
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_HOST
          value: "crawler-mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: RABBITMQ_HOST
          value: "queue"
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-pass
              key: password
        - name: HUOBI_API_KEY
          valueFrom:
            secretKeyRef:
              name: huobi-api
              key: key
        - name: HUOBI_API_SECRET
          valueFrom:
            secretKeyRef:
              name: huobi-api
              key: sec
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
