apiVersion: v1
kind: Service
metadata:
  name: crawlab-worker
  labels:
    app: crawlab-worker
spec:
  ports:
    - port: 8000
  selector:
    app: crawlab-worker
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: crawlab-worker
  labels:
    app: crawlab-worker
spec:
  selector:
    matchLabels:
      app: crawlab-worker
  serviceName: "crawlab-worker"
  replicas: 3
  template:
    metadata:
      labels:
        app: crawlab-worker
    spec:
      containers:
      - image: bitsean/crawlab-backend:0.3
        name: crawlab-worker
        env:
        - name: MYSQL_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_HOST
          value: "crawler-mysql"
        - name: MYSQL_PORT
          value: "3306"
        - name: CRAWLAB_SERVER_MASTER
          value: "N"
        - name: CRAWLAB_REDIS_ADDRESS
          value: "crawler-redis"
        - name: CRAWLAB_MONGO_HOST
          value: "crawler-mongo"
        ports:
        - containerPort: 8000